 #app.py
# ─────────────────────────────────────────────────────────────────────────────
# Chronic Kidney Disease Risk Prediction System – Streamlit Application
# Run:  streamlit run app.py
# ─────────────────────────────────────────────────────────────────────────────

import os
import sys
import warnings
import datetime
import time
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import streamlit as st
import streamlit.components.v1 as components
import plotly.graph_objects as go
import plotly.express as px
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

import logging
logging.basicConfig(
    filename='app.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

from auth import (
    create_users_table,
    register_user,
    login_user,
    logout_user,
    validate_email,
    create_predictions_table,
    save_prediction,
    get_predictions,
    create_patient,
    get_patients,
    update_patient,
    delete_patient,
    schedule_appointment,
    get_appointments,
    delete_appointment,
    submit_feedback,
    get_all_feedback,
    log_audit_action,
    get_audit_logs,
    get_admin_metrics
)

try:
    from auth import normalize_prediction_row
except ImportError:
    def normalize_prediction_row(row):
        normalized = dict(row or {})
        aliases = {
            "Age": ("Age", "age"),
            "Gender": ("Gender", "gender"),
            "BMI": ("BMI", "bmi"),
            "Diabetes": ("Diabetes", "diabetes"),
            "Hypertension": ("Hypertension", "hypertension"),
            "Family_History_Kidney": ("Family_History_Kidney", "family_history"),
        }
        for canonical, names in aliases.items():
            value = None
            for name in names:
                if name in normalized:
                    value = normalized[name]
                    break
            if value is not None:
                normalized[canonical] = value
                for name in names:
                    if name != canonical:
                        normalized[name] = value
        return normalized

warnings.filterwarnings("ignore")

# ─── Ensure project root is on the path ──────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)

from ckd_utils.prediction    import load_model_bundle, predict_single, explain_prediction_local
from ckd_utils.preprocessing import preprocess_single_input
from ckd_utils.report_generator import generate_detailed_recommendations, create_pdf_report

# ─── SMTP Email Sender ────────────────────────────────────────────────────────
def send_pdf_email(recipient_email, pdf_bytes, filename,
                   smtp_server=None, smtp_port=587, smtp_user=None, smtp_pass=None):
    """
    Sends an email with the PDF report attachment.
    If no SMTP credentials are provided, runs in dry-run mode and writes to ckd_email_report.eml.
    """
    msg = MIMEMultipart()
    msg['From'] = smtp_user if smtp_user else "no-reply@kidneyassessment.com"
    msg['To'] = recipient_email
    msg['Subject'] = "Your Chronic Kidney Disease Assessment Report"

    body = (
        "Dear Patient,\n\n"
        "Please find attached your Chronic Kidney Disease Assessment Report generated by "
        "our AI-Powered Clinical Decision Support System.\n\n"
        "Best regards,\n"
        "Metropolitan Kidney Care Center"
    )
    msg.attach(MIMEText(body, 'plain'))

    part = MIMEBase('application', 'octet-stream')
    part.set_payload(pdf_bytes)
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f"attachment; filename= {filename}")
    msg.attach(part)

    if not smtp_server or not smtp_user or not smtp_pass:
        eml_path = os.path.join(BASE_DIR, "ckd_email_report.eml")
        with open(eml_path, 'wb') as f:
            f.write(msg.as_bytes())
        return True, "dry_run", eml_path

    try:
        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(msg['From'], recipient_email, msg.as_string())
        server.quit()
        return True, "sent", None
    except Exception as e:
        return False, str(e), None


# ─── Paths ────────────────────────────────────────────────────────────────────
MODEL_PATH = os.path.join(BASE_DIR, "model", "kidney_model.pkl")
TRAIN_PATH = os.path.join(BASE_DIR, "dataset", "Training_CKD_dataset.csv")
TEST_PATH  = os.path.join(BASE_DIR, "dataset", "Testing_CKD_dataset.csv")
ASSETS_DIR = os.path.join(BASE_DIR, "assets")

# ─── Page config ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="CKD Risk Prediction System",
    page_icon="🫁",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Theme setup ─────────────────────────────────────────────────────────────
if "theme" not in st.session_state:
    st.session_state["theme"] = "Dark Theme"

theme_mode = st.session_state["theme"]

if theme_mode == "Dark Theme":
    bg_color      = "linear-gradient(135deg, #0f1117 0%, #1a1f2e 50%, #0f1117 100%)"
    card_bg       = "linear-gradient(135deg, #1e2535 0%, #252d42 100%)"
    card_border   = "#2d3748"
    text_main     = "#e2e8f0"
    text_sub      = "#a0aec0"
    text_p        = "#cbd5e0"
    sidebar_bg    = "linear-gradient(180deg, #141824 0%, #1e2535 100%)"
    metric_val    = "#63b3ed"
else:
    bg_color      = "linear-gradient(135deg, #f7fafc 0%, #edf2f7 50%, #f7fafc 100%)"
    card_bg       = "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)"
    card_border   = "#e2e8f0"
    text_main     = "#1a202c"
    text_sub      = "#4a5568"
    text_p        = "#2d3748"
    sidebar_bg    = "linear-gradient(180deg, #edf2f7 0%, #e2e8f0 100%)"
    metric_val    = "#2b6cb0"

st.markdown(f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
html, body, [class*="css"] {{ font-family: 'Inter', sans-serif; }}
.stApp {{ background: {bg_color} !important; }}
section[data-testid="stSidebar"] {{
    background: {sidebar_bg} !important;
    border-right: 1px solid {card_border} !important;
}}
section[data-testid="stSidebar"] .stRadio > label {{ color: {text_sub}; font-size: 0.85rem; }}
.metric-card {{
    background: {card_bg} !important;
    border: 1px solid {card_border} !important;
    border-radius: 16px;
    padding: 24px 20px;
    text-align: center;
    transition: transform .2s, box-shadow .2s;
}}
.metric-card:hover {{
    transform: translateY(-3px);
    box-shadow: 0 8px 30px rgba(99,179,237,.2);
}}
.metric-card .metric-value {{ font-size: 2.2rem; font-weight: 700; color: {metric_val}; }}
.metric-card .metric-label {{ font-size: 0.85rem; color: {text_sub}; margin-top: 4px; text-transform: uppercase; letter-spacing: .05em; }}
.prediction-card {{
    background: linear-gradient(135deg, #1a2744 0%, #1e3a5f 100%);
    border: 2px solid #3182ce;
    border-radius: 20px;
    padding: 32px;
    text-align: center;
    margin: 16px 0;
    box-shadow: 0 0 40px rgba(49,130,206,.25);
    animation: fadeInUp 0.5s ease;
}}
.prediction-card .stage-label {{ font-size: 0.9rem; color: #90cdf4; text-transform: uppercase; letter-spacing: .1em; }}
.prediction-card .stage-value {{ font-size: 2.4rem; font-weight: 700; color: #ffffff; margin: 8px 0; }}
.prediction-card .confidence  {{ font-size: 1rem; color: #68d391; font-weight: 500; }}
.section-header {{
    background: linear-gradient(90deg, #2b6cb0 0%, #3182ce 100%);
    color: white;
    padding: 10px 20px;
    border-radius: 10px;
    font-weight: 600;
    font-size: 1.1rem;
    margin-bottom: 16px;
}}
.stButton > button {{
    background: linear-gradient(135deg, #2b6cb0 0%, #3182ce 100%);
    color: white;
    border: none;
    border-radius: 10px;
    padding: 10px 28px;
    font-size: 1rem;
    font-weight: 600;
    transition: opacity .2s, transform .2s;
}}
.stButton > button:hover {{ opacity: .9; transform: translateY(-2px); }}
h1,h2,h3,h4 {{ color: {text_main} !important; }}
p, li       {{ color: {text_sub} !important; }}
.stMarkdown p {{ color: {text_p} !important; }}
[data-testid="stMetricValue"] {{ color: {metric_val} !important; }}
[data-testid="stMetricLabel"] {{ color: {text_sub} !important; }}
.streamlit-expanderHeader {{ background: {card_bg} !important; color: {text_main} !important; border-radius: 8px; }}
.stAlert {{ border-radius: 10px; }}
@keyframes fadeInUp {{
    from {{ opacity: 0; transform: translateY(20px); }}
    to   {{ opacity: 1; transform: translateY(0); }}
}}
.fi-bar-container {{
    background: {card_bg};
    border: 1px solid {card_border};
    border-radius: 14px;
    padding: 20px 24px;
    margin: 12px 0;
}}
.fi-row {{
    display: flex;
    align-items: center;
    margin-bottom: 12px;
    gap: 12px;
}}
.fi-label {{
    width: 210px;
    font-size: 0.83rem;
    font-weight: 500;
    color: {text_sub};
    text-align: right;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}}
.fi-bar-outer {{
    flex: 1;
    height: 22px;
    background: rgba(99,179,237,0.10);
    border-radius: 11px;
    overflow: hidden;
}}
.fi-bar-inner {{
    height: 100%;
    border-radius: 11px;
    transition: width 0.7s ease;
}}
.fi-value {{
    width: 60px;
    font-size: 0.83rem;
    font-weight: 600;
    color: {text_main};
    text-align: right;
}}
</style>
""", unsafe_allow_html=True)


# ─────────────────────────────────────────────────────────────────────────────
# Auth Initialization
# ─────────────────────────────────────────────────────────────────────────────
create_users_table()
create_predictions_table()

if "logged_in" not in st.session_state:
    st.session_state["logged_in"] = False
if "auth_page" not in st.session_state:
    st.session_state["auth_page"] = "login"

if not st.session_state["logged_in"]:
    st.markdown("<h1 style='text-align:center;color:#e2e8f0;margin-top:50px;'>🫁 CKD Risk System</h1>",
                unsafe_allow_html=True)

    if st.session_state["auth_page"] == "login":
        st.markdown("<h3 style='text-align:center;color:#a0aec0;'>Login to Your Account</h3>",
                    unsafe_allow_html=True)
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            if "register_success" in st.session_state:
                st.success(st.session_state.pop("register_success"))
            with st.form("login_form"):
                username = st.text_input("Username")
                password = st.text_input("Password", type="password")
                submit   = st.form_submit_button("Login", width='stretch')
                if submit:
                    if not username or not password:
                        st.error("Please enter both username and password.")
                    elif login_user(username, password):
                        st.session_state["logged_in"] = True
                        st.session_state["username"]  = username
                        st.rerun()
                    else:
                        st.error("Invalid username or password.")
            st.markdown("<div style='text-align:center;margin-top:10px;'>Don't have an account?</div>",
                        unsafe_allow_html=True)
            if st.button("Register Here", width='stretch'):
                st.session_state["auth_page"] = "register"
                st.rerun()
    else:
        st.markdown("<h3 style='text-align:center;color:#a0aec0;'>Create a New Account</h3>",
                    unsafe_allow_html=True)
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            with st.form("register_form"):
                new_user    = st.text_input("Username")
                new_email   = st.text_input("Email")
                new_pwd     = st.text_input("Password", type="password")
                confirm_pwd = st.text_input("Confirm Password", type="password")
                submit      = st.form_submit_button("Register", width='stretch')
                if submit:
                    if not new_user:
                        st.error("Username is required.")
                    elif not new_email or not validate_email(new_email):
                        st.error("Please enter a valid email address.")
                    elif len(new_pwd) < 8:
                        st.error("Password must be at least 8 characters long.")
                    elif new_pwd != confirm_pwd:
                        st.error("Passwords do not match.")
                    else:
                        success, msg = register_user(new_user, new_email, new_pwd)
                        if success:
                            st.session_state["register_success"] = msg
                            st.session_state["auth_page"] = "login"
                            st.rerun()
                        else:
                            st.error(msg)
            st.markdown("<div style='text-align:center;margin-top:10px;'>Already have an account?</div>",
                        unsafe_allow_html=True)
            if st.button("Back to Login", width='stretch'):
                st.session_state["auth_page"] = "login"
                st.rerun()
    st.stop()


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

@st.cache_resource(show_spinner="Loading model …")
def get_bundle():
    """Load and cache the trained model bundle."""
    return load_model_bundle(MODEL_PATH)


@st.cache_data(show_spinner="Loading datasets …")
def get_datasets():
    """Load and cache training and testing CSVs."""
    train = pd.read_csv(TRAIN_PATH)
    test  = pd.read_csv(TEST_PATH)
    return train, test


STAGE_COLORS = {
    "Healthy Kidney":          "#68d391",
    "Mild CKD (Stage 1\u20132)": "#f6e05e",
    "Moderate CKD (Stage 3)":  "#ed8936",
    "Severe CKD (Stage 4)":    "#fc8181",
    "Kidney Failure (Stage 5)":"#e53e3e",
}

FEATURE_LABELS = {
    "Age":                      "Age (years)",
    "Gender":                   "Gender",
    "BMI":                      "BMI (kg/m\u00b2)",
    "Urine_Albumin":            "Urine Albumin (mg/L)",
    "Urine_Protein":            "Urine Protein (mg/dL)",
    "Albumin_Creatinine_Ratio": "Albumin-Creatinine Ratio",
    "Diabetes":                 "Diabetes",
    "Hypertension":             "Hypertension",
    "Family_History_Kidney":    "Family History (Kidney)",
}


def stage_emoji(label: str) -> str:
    mapping = {
        "Healthy Kidney":          "\u2705",
        "Mild CKD (Stage 1\u20132)": "\U0001f7e1",
        "Moderate CKD (Stage 3)":  "\U0001f7e0",
        "Severe CKD (Stage 4)":    "\U0001f534",
        "Kidney Failure (Stage 5)":"\U0001f6a8",
    }
    return mapping.get(label, "\u2753")


def stage_color_hex(label: str) -> str:
    return STAGE_COLORS.get(label, "#63b3ed")


def stage_recommendation(label: str) -> str:
    recs = {
        "Healthy Kidney":
            "Great news! Your kidneys appear healthy. Maintain a balanced diet, stay hydrated, "
            "exercise regularly, and get annual check-ups.",
        "Mild CKD (Stage 1\u20132)":
            "Early-stage CKD detected. Your kidneys are still functioning well. Consult a nephrologist, "
            "control blood pressure & blood sugar, and limit sodium intake.",
        "Moderate CKD (Stage 3)":
            "Moderate CKD Stage 3 detected. Kidney function is moderately reduced. Immediate medical "
            "attention is advised. Follow a kidney-friendly diet and monitor labs regularly.",
        "Severe CKD (Stage 4)":
            "Severe CKD Stage 4 detected. Kidney function is severely reduced. Begin planning for renal "
            "replacement therapy (dialysis or transplant). Work closely with your care team.",
        "Kidney Failure (Stage 5)":
            "\u26a0\ufe0f Kidney Failure (Stage 5) detected. Immediate medical intervention is required. "
            "Dialysis or kidney transplant may be necessary. Contact your nephrologist immediately.",
    }
    return recs.get(label, "Please consult a medical professional.")


# ─────────────────────────────────────────────────────────────────────────────
# Sidebar Navigation
# ─────────────────────────────────────────────────────────────────────────────
if "_nav_target" in st.session_state and st.session_state["_nav_target"]:
    st.session_state["page_nav"] = st.session_state.pop("_nav_target")

with st.sidebar:
    st.markdown("""
    <div style='text-align:center;padding:20px 0 10px;'>
        <div style='font-size:3rem;'>\U0001fac1</div>
        <div style='font-size:1.1rem;font-weight:700;color:#e2e8f0;margin-top:6px;'>CKD Risk System</div>
        <div style='font-size:0.75rem;color:#a0aec0;margin-top:2px;'>AI-Powered Prediction</div>
    </div>
    <hr style='border-color:#2d3748;margin:12px 0;'>
    """, unsafe_allow_html=True)

    nav_options = [
        "🏠  Home", "🔬  Prediction", "👤  Patients", "📅  Reminders",
        "📋  History", "📊  Dashboard", "ℹ️  About"
    ]
    if st.session_state.get("username") == "admin":
        nav_options.append("🔑  Admin Panel")

    page = st.radio(
        "Navigate",
        nav_options,
        label_visibility="collapsed",
        key="page_nav",
    )

    st.markdown("<hr style='border-color:#2d3748;margin:16px 0 10px;'>", unsafe_allow_html=True)

    # ── Theme Toggle
    st.markdown("<div style='font-size:0.78rem;color:#718096;text-align:center;margin-bottom:6px;'>🎨 Theme</div>",
                unsafe_allow_html=True)
    chosen_theme = st.radio(
        "Theme",
        ["Dark Theme", "Light Theme"],
        index=0 if st.session_state["theme"] == "Dark Theme" else 1,
        label_visibility="collapsed",
        horizontal=True,
        key="theme_radio",
    )
    if chosen_theme != st.session_state["theme"]:
        st.session_state["theme"] = chosen_theme
        st.rerun()

    st.markdown("""
    <hr style='border-color:#2d3748;margin:16px 0 12px;'>
    <div style='font-size:0.75rem;color:#718096;text-align:center;'>
        Powered by Machine Learning<br>Scikit-learn \u00b7 Streamlit
    </div>
    """, unsafe_allow_html=True)

    current_user = st.session_state.get("username", "")
    if current_user:
        st.markdown(f"""
        <div style='text-align:center;margin:14px 0 10px;padding:10px;
                    background:rgba(49,130,206,0.12);border-radius:10px;
                    border:1px solid rgba(49,130,206,0.25);'>
            <div style='font-size:1.4rem;'>\U0001f464</div>
            <div style='font-size:0.82rem;color:#63b3ed;font-weight:600;'>{current_user}</div>
        </div>""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    if st.button("\U0001f6aa Logout", width='stretch'):
        logout_user()
        st.rerun()


# ─────────────────────────────────────────────────────────────────────────────
# Load Resources
# ─────────────────────────────────────────────────────────────────────────────
model_loaded = False
bundle       = None
train_df     = None
test_df      = None

try:
    bundle       = get_bundle()
    model_loaded = True
except FileNotFoundError:
    pass

try:
    train_df, test_df = get_datasets()
except Exception:
    pass


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: HOME
# ═════════════════════════════════════════════════════════════════════════════
if page == "🏠  Home":
    st.markdown("""
<style>
/* Global resets for the home page */
[data-testid="stAppViewContainer"] { padding: 0 !important; }
.stApp { background: #0f172a !important; color: #f8fafc !important; }
section[data-testid="stSidebar"] { display: none !important; }
[data-testid="collapsedControl"] { display: none !important; }
.main .block-container {
    padding: 0 !important;
    max-width: 100% !important;
}
#MainMenu, footer, header { visibility: hidden !important; }

/* Navigation Bar */
.nav-bar {
    background: rgba(15, 23, 42, 0.8);
    backdrop-filter: blur(12px);
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
    padding: 16px 40px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    position: sticky;
    top: 0;
    z-index: 100;
}
.nav-logo {
    font-size: 1.5rem;
    font-weight: 800;
    color: #38bdf8;
    display: flex;
    align-items: center;
    gap: 10px;
}

/* Hero Section */
.hero-section {
    position: relative;
    padding: 80px 10%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    min-height: 85vh;
    background: radial-gradient(circle at top left, #1e293b, #0f172a);
    overflow: hidden;
}

/* Decorative background elements */
.hero-glow-1 {
    position: absolute;
    top: -100px;
    left: -100px;
    width: 400px;
    height: 400px;
    background: rgba(56, 189, 248, 0.2);
    filter: blur(100px);
    border-radius: 50%;
    z-index: 0;
}
.hero-glow-2 {
    position: absolute;
    bottom: -150px;
    right: -50px;
    width: 500px;
    height: 500px;
    background: rgba(139, 92, 246, 0.15);
    filter: blur(120px);
    border-radius: 50%;
    z-index: 0;
}

.hero-content {
    flex: 1;
    z-index: 10;
    max-width: 650px;
}
.badge {
    display: inline-block;
    background: rgba(56, 189, 248, 0.1);
    color: #38bdf8;
    border: 1px solid rgba(56, 189, 248, 0.2);
    padding: 6px 16px;
    border-radius: 30px;
    font-size: 0.85rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1px;
    margin-bottom: 24px;
    animation: fadeInDown 0.8s ease-out;
}
.hero-title {
    font-size: 4rem;
    font-weight: 800;
    line-height: 1.1;
    margin-bottom: 24px;
    color: #f8fafc !important;
    animation: fadeInUp 0.8s ease-out 0.2s both;
}
.hero-title span {
    background: linear-gradient(135deg, #38bdf8, #818cf8);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}
.hero-subtitle {
    font-size: 1.15rem;
    color: #94a3b8;
    line-height: 1.7;
    margin-bottom: 40px;
    animation: fadeInUp 0.8s ease-out 0.4s both;
}

/* Glass Cards */
.features-container {
    display: flex;
    gap: 20px;
    margin-top: 50px;
    animation: fadeInUp 0.8s ease-out 0.6s both;
}
.feature-card {
    background: rgba(30, 41, 59, 0.5);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.05);
    padding: 20px;
    border-radius: 16px;
    flex: 1;
    transition: transform 0.3s, border-color 0.3s;
}
.feature-card:hover {
    transform: translateY(-5px);
    border-color: rgba(56, 189, 248, 0.3);
}
.feature-icon {
    font-size: 1.8rem;
    margin-bottom: 12px;
}
.feature-title {
    font-weight: 600;
    color: #f1f5f9;
    font-size: 1.05rem;
    margin-bottom: 6px;
}
.feature-desc {
    font-size: 0.85rem;
    color: #64748b;
}

/* Animations */
@keyframes fadeInUp {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}
@keyframes fadeInDown {
    from { opacity: 0; transform: translateY(-20px); }
    to { opacity: 1; transform: translateY(0); }
}
@keyframes float {
    0% { transform: translateY(0px); }
    50% { transform: translateY(-15px); }
    100% { transform: translateY(0px); }
}

/* Visual Graphic */
.hero-graphic {
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 10;
    animation: float 6s ease-in-out infinite;
}
.stButton > button[kind="primary"] {
    background: linear-gradient(135deg, #38bdf8, #818cf8) !important;
    color: #ffffff !important;
    border: none !important;
    border-radius: 50px !important;
    padding: 16px 40px !important;
    font-size: 1.1rem !important;
    font-weight: 600 !important;
    box-shadow: 0 10px 25px -5px rgba(56, 189, 248, 0.4) !important;
    transition: all 0.3s ease !important;
    animation: fadeInUp 0.8s ease-out 0.5s both;
    width: 250px !important;
}
.stButton > button[kind="primary"]:hover {
    transform: translateY(-3px) scale(1.02) !important;
    box-shadow: 0 15px 30px -5px rgba(56, 189, 248, 0.6) !important;
}

/* Disclaimer */
.disclaimer {
    background: rgba(245, 158, 11, 0.1);
    border-left: 4px solid #f59e0b;
    padding: 16px 24px;
    border-radius: 0 8px 8px 0;
    color: #fbbf24;
    font-size: 0.9rem;
    margin: -30px 10% 40px;
    z-index: 10;
    position: relative;
}
</style>
""", unsafe_allow_html=True)

    # Top Navigation visually simulated
    st.markdown("""
    <div class="nav-bar">
        <div class="nav-logo">🩺 CKD Predictor</div>
    </div>
    
    <!-- Background glowing orbs -->
    <div class="hero-glow-1"></div>
    <div class="hero-glow-2"></div>
    """, unsafe_allow_html=True)

    # Use native Streamlit columns for the layout so components interleave correctly
    st.markdown("<br><br>", unsafe_allow_html=True)
    hero_left, hero_right = st.columns([1.2, 1.0])
    
    with hero_left:
        st.markdown("""
<div class="hero-content">
    <div class="badge">Advanced Clinical Diagnostics</div>
    <h1 class="hero-title">Predict Kidney Disease with <span>AI Precision</span></h1>
    <p class="hero-subtitle">
        Empowering healthcare professionals with state-of-the-art machine learning models to detect Chronic Kidney Disease early, safely, and interpretably.
    </p>
</div>
""", unsafe_allow_html=True)
        
        st.write("") # small spacing
        col_btn, _ = st.columns([1, 1])
        with col_btn:
            if st.button("🚀 Start Prediction", key="hero_cta", type="primary"):
                st.session_state["_nav_target"] = "🔬  Prediction"
                st.rerun()
                
        st.markdown("""
<div class="features-container" style="margin-top:40px;">
    <div class="feature-card">
        <div class="feature-icon">⚡</div>
        <div class="feature-title">Fast & Accurate</div>
        <div class="feature-desc">91.6% accuracy validated on diverse clinical records.</div>
    </div>
    <div class="feature-card">
        <div class="feature-icon">🔍</div>
        <div class="feature-title">XAI Explainability</div>
        <div class="feature-desc">Transparent feature insights for every prediction.</div>
    </div>
    <div class="feature-card">
        <div class="feature-icon">📄</div>
        <div class="feature-title">Clinical Reports</div>
        <div class="feature-desc">Instantly generate PDF summaries and dispatch via email.</div>
    </div>
</div>
""", unsafe_allow_html=True)

    with hero_right:
        components.html("""
<!DOCTYPE html>
<html>
<head>
<style>
body { margin:0; background: transparent; overflow: hidden; }
.hero-graphic {
    display: flex;
    justify-content: center;
    align-items: center;
    animation: float 6s ease-in-out infinite;
    padding-top: 10px;
}
@keyframes float {
    0%   { transform: translateY(0px); }
    50%  { transform: translateY(-15px); }
    100% { transform: translateY(0px); }
}
</style>
</head>
<body>
<div class="hero-graphic">
<svg viewBox="0 0 500 500" width="100%" height="440" xmlns="http://www.w3.org/2000/svg">
    <defs>
        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
            <stop offset="0%" style="stop-color:#38bdf8;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#818cf8;stop-opacity:1" />
        </linearGradient>
        <radialGradient id="bgGlow" cx="50%" cy="50%" r="50%">
            <stop offset="0%" style="stop-color:#38bdf8;stop-opacity:0.15" />
            <stop offset="100%" style="stop-color:#0f172a;stop-opacity:0" />
        </radialGradient>
        <filter id="glow" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="8" result="coloredBlur"/>
            <feMerge>
                <feMergeNode in="coloredBlur"/>
                <feMergeNode in="SourceGraphic"/>
            </feMerge>
        </filter>
        <filter id="softglow" x="-20%" y="-20%" width="140%" height="140%">
            <feGaussianBlur stdDeviation="4" result="coloredBlur"/>
            <feMerge>
                <feMergeNode in="coloredBlur"/>
                <feMergeNode in="SourceGraphic"/>
            </feMerge>
        </filter>
    </defs>
    
    <!-- Radial bg glow -->
    <circle cx="250" cy="250" r="220" fill="url(#bgGlow)"/>
    <circle cx="250" cy="250" r="185" fill="none" stroke="rgba(56,189,248,0.08)" stroke-width="1"/>
    <circle cx="250" cy="250" r="145" fill="none" stroke="rgba(129,140,248,0.10)" stroke-width="1"/>
    <circle cx="250" cy="250" r="105" fill="none" stroke="rgba(56,189,248,0.12)" stroke-width="1"/>
    
    <!-- Left Kidney -->
    <g transform="translate(95, 85)" filter="url(#glow)">
        <path d="M 60 40 C 20 40, -10 100, -10 160 C -10 220, 30 270, 70 290 C 100 305, 120 280, 130 250 C 145 200, 140 150, 135 110 C 130 70, 110 40, 60 40 Z"
              fill="url(#grad1)" opacity="0.85"/>
        <ellipse cx="55" cy="165" rx="18" ry="28" fill="rgba(15,23,42,0.4)" />
        <circle cx="40" cy="120" r="8" fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <circle cx="80" cy="180" r="6" fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <circle cx="50" cy="230" r="9"  fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <circle cx="105" cy="100" r="5" fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <path d="M40 120 L80 180 L50 230 M80 180 L105 100" stroke="rgba(255,255,255,0.5)" stroke-width="2" fill="none" stroke-linecap="round"/>
    </g>
    
    <!-- Right Kidney -->
    <g transform="translate(280, 85)" filter="url(#glow)">
        <path d="M 60 40 C 100 40, 130 100, 130 160 C 130 220, 90 270, 50 290 C 20 305, 0 280, -10 250 C -25 200, -20 150, -15 110 C -10 70, 10 40, 60 40 Z"
              fill="url(#grad1)" opacity="0.85"/>
        <ellipse cx="60" cy="165" rx="18" ry="28" fill="rgba(15,23,42,0.4)" />
        <circle cx="80" cy="120" r="8" fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <circle cx="40" cy="180" r="6" fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <circle cx="65" cy="230" r="9"  fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <circle cx="15" cy="100" r="5" fill="#fff" opacity="0.9" filter="url(#softglow)"/>
        <path d="M80 120 L40 180 L65 230 M40 180 L15 100" stroke="rgba(255,255,255,0.5)" stroke-width="2" fill="none" stroke-linecap="round"/>
    </g>
    
    <!-- Dashed connecting line -->
    <path d="M195 250 L305 250" stroke="url(#grad1)" stroke-width="2.5" stroke-dasharray="8 5" fill="none" opacity="0.8"/>
    
    <!-- Central AI Hub -->
    <circle cx="250" cy="250" r="32" fill="#1e293b" stroke="url(#grad1)" stroke-width="2.5" filter="url(#softglow)"/>
    <circle cx="250" cy="250" r="26" fill="rgba(56,189,248,0.1)" />
    <text x="250" y="255" font-family="Arial, sans-serif" font-size="13" fill="#f8fafc" font-weight="bold" text-anchor="middle">AI</text>
    
    <!-- Pulse ring animation -->
    <circle cx="250" cy="250" r="38" fill="none" stroke="rgba(56,189,248,0.4)" stroke-width="1.5">
        <animate attributeName="r" values="32;50;32" dur="3s" repeatCount="indefinite" />
        <animate attributeName="opacity" values="0.6;0;0.6" dur="3s" repeatCount="indefinite" />
    </circle>
    
    <!-- ECG line at the bottom -->
    <path d="M60 420 L110 420 L130 390 L150 450 L170 400 L190 420 L440 420"
          stroke="url(#grad1)" stroke-width="2.5" fill="none" opacity="0.5"
          stroke-linecap="round" stroke-linejoin="round"/>
</svg>
</div>
</body>
</html>
""", height=460, scrolling=False)

    st.markdown("""
    <div class="disclaimer" style="margin-top:60px;">
        <strong>⚠️ Medical Disclaimer:</strong> This application is intended for <strong>educational and research purposes only</strong> and should not replace professional medical advice. Always consult a qualified healthcare provider for clinical decisions.
    </div>
    <br>
    """, unsafe_allow_html=True)


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: PREDICTION
# ═════════════════════════════════════════════════════════════════════════════
elif page == "🔬  Prediction":
    st.markdown("<h1 style='color:#e2e8f0;'>\U0001f52c CKD Risk Prediction</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#a0aec0;'>Fill in patient details and press <b>Predict</b> to assess kidney health risk.</p>",
                unsafe_allow_html=True)

    if not model_loaded:
        st.error("\u274c Model not loaded. Run `python train_model.py` first.")
        st.stop()

    st.markdown("---")

    username = st.session_state.get("username", "")
    patients_list = get_patients(username)
    selected_patient = None
    if patients_list:
        p_names = ["-- Select Saved Patient Profile --"] + [f"{p['name']} (ID: {p['id']})" for p in patients_list]
        selected_p_str = st.selectbox("Select Patient Profile (Optional - auto-fills details)", p_names)
        if selected_p_str != "-- Select Saved Patient Profile --":
            p_id = int(selected_p_str.split(" (ID: ")[1][:-1])
            selected_patient = next(p for p in patients_list if p["id"] == p_id)

    with st.form("prediction_form"):

        # Patient Name
        st.markdown("<div class='section-header'>\U0001f4cb Patient Information</div>", unsafe_allow_html=True)
        _pc1, _pc2 = st.columns([2, 2])
        default_name = selected_patient["name"] if selected_patient else ""
        patient_name = _pc1.text_input("Patient Name", value=default_name, placeholder="e.g. John Doe",
                                        help="Enter the patient's full name for record keeping")

        # Personal Information
        st.markdown("<div class='section-header'>\U0001f464 Personal Information</div>", unsafe_allow_html=True)
        c1, c2, c3, c4 = st.columns(4)
        
        default_age = int(selected_patient["age"]) if selected_patient else 45
        default_gender = selected_patient["gender"] if selected_patient else "Male"
        default_height = float(selected_patient["height"]) if selected_patient else 170.0
        default_weight = float(selected_patient["weight"]) if selected_patient else 70.0
        
        age    = c1.number_input("Age (years)", min_value=1, max_value=120, value=default_age)
        gender = c2.selectbox("Gender", ["Male", "Female"], index=0 if default_gender == "Male" else 1)
        height = c3.number_input("Height (cm)", min_value=100.0, max_value=250.0, value=default_height, step=0.5)
        weight = c4.number_input("Weight (kg)", min_value=20.0, max_value=250.0, value=default_weight, step=0.5)

        bmi_preview = weight / ((height / 100) ** 2)
        if bmi_preview < 18.5:
            bmi_category, bmi_color = "Underweight", "#90cdf4"
        elif bmi_preview < 25:
            bmi_category, bmi_color = "Normal weight", "#68d391"
        elif bmi_preview < 30:
            bmi_category, bmi_color = "Overweight", "#f6e05e"
        else:
            bmi_category, bmi_color = "Obese", "#fc8181"

        st.markdown(f"""
        <div style='background:#1e2535;border:1px solid #2d3748;border-radius:12px;
                    padding:14px 20px;margin:12px 0 8px;display:flex;align-items:center;gap:20px;'>
          <div>
            <div style='font-size:0.78rem;color:#a0aec0;text-transform:uppercase;letter-spacing:.06em;'>
              Calculated BMI (read-only)
            </div>
            <div style='font-size:2rem;font-weight:700;color:{bmi_color};margin-top:2px;'>
              {bmi_preview:.1f} <span style='font-size:1rem;font-weight:400;'>kg/m&sup2;</span>
            </div>
          </div>
          <div style='background:{bmi_color}22;border-radius:8px;padding:6px 16px;'>
            <span style='color:{bmi_color};font-weight:600;font-size:0.9rem;'>{bmi_category}</span>
          </div>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)

        # Urine Test Markers
        st.markdown("<div class='section-header'>🔬 Urine Test Markers</div>", unsafe_allow_html=True)
        u1, u2, u3 = st.columns(3)
        urine_alb  = u1.number_input("Urine Albumin (mg/L)",             min_value=0.0, max_value=2500.0, value=15.0, step=1.0)
        urine_prot = u2.number_input("Urine Protein (mg/dL)",             min_value=0.0, max_value=1200.0, value=10.0, step=1.0)
        acr        = u3.number_input("Albumin-to-Creatinine Ratio (mg/g)", min_value=0.0, max_value=3500.0, value=25.0, step=1.0)

        st.markdown("<br>", unsafe_allow_html=True)

        # Advanced Clinical Markers
        st.markdown("<div class='section-header'>🩸 Advanced Clinical Markers</div>", unsafe_allow_html=True)
        with st.expander("Show/Hide Advanced Markers (Pre-filled with typical averages)"):
            c_adv1, c_adv2, c_adv3, c_adv4 = st.columns(4)
            systolic_bp = c_adv1.number_input("Systolic BP", value=120.0)
            diastolic_bp = c_adv2.number_input("Diastolic BP", value=80.0)
            heart_rate = c_adv3.number_input("Heart Rate", value=75.0)
            serum_creatinine = c_adv4.number_input("Serum Creatinine", value=1.0)

            bun = c_adv1.number_input("Blood Urea Nitrogen", value=15.0)
            egfr = c_adv2.number_input("eGFR", value=90.0)
            usg = c_adv3.number_input("Urine Specific Gravity", value=1.015)
            sodium = c_adv4.number_input("Sodium", value=140.0)

            potassium = c_adv1.number_input("Potassium", value=4.0)
            calcium = c_adv2.number_input("Calcium", value=9.5)
            phosphorus = c_adv3.number_input("Phosphorus", value=3.5)
            chloride = c_adv4.number_input("Chloride", value=100.0)

            bicarbonate = c_adv1.number_input("Bicarbonate", value=24.0)
            hemoglobin = c_adv2.number_input("Hemoglobin", value=14.0)
            rbc_count = c_adv3.number_input("RBC Count", value=4.5)
            wbc_count = c_adv4.number_input("WBC Count", value=7000.0)

            platelet_count = c_adv1.number_input("Platelet Count", value=250000.0)
            pcv = c_adv2.number_input("Packed Cell Vol.", value=40.0)
            bgr = c_adv3.number_input("Blood Glucose (Rand)", value=100.0)
            fasting_gluc = c_adv4.number_input("Fasting Glucose", value=90.0)

            hba1c = c_adv1.number_input("HbA1c", value=5.5)
            cholesterol = c_adv2.number_input("Cholesterol", value=180.0)
            triglycerides = c_adv3.number_input("Triglycerides", value=120.0)
            serum_albumin = c_adv4.number_input("Serum Albumin", value=4.0)
            total_protein = c_adv1.number_input("Total Protein", value=7.0)

            default_smoking = selected_patient["smoking_status"] if selected_patient else "No"
            smoking_status = c_adv2.selectbox("Smoking Status", ["No", "Yes"], index=0 if default_smoking == "No" else 1)

        st.markdown("<br>", unsafe_allow_html=True)

        # Health Conditions
        st.markdown("<div class='section-header'>&#9877;&#65039; Health Conditions &amp; Risk Factors</div>",
                    unsafe_allow_html=True)
        c1, c2, c3 = st.columns(3)
        
        default_diabetes = selected_patient["diabetes"] if selected_patient else "No"
        default_hyper = selected_patient["hypertension"] if selected_patient else "No"
        default_family = selected_patient["family_history"] if selected_patient else "No"
        
        diabetes     = c1.selectbox("Diabetes",                        ["No", "Yes"], index=0 if default_diabetes == "No" else 1)
        hypertension = c2.selectbox("Hypertension",                    ["No", "Yes"], index=0 if default_hyper == "No" else 1)
        family_hist  = c3.selectbox("Family History of Kidney Disease", ["No", "Yes"], index=0 if default_family == "No" else 1)

        st.markdown("<br>", unsafe_allow_html=True)
        submitted = st.form_submit_button("\U0001f52e Predict My Kidney Health", width='stretch')

    if submitted:
        errors = []
        if not patient_name.strip():
            errors.append("Patient name is required.")
        if not (1 <= age <= 120):
            errors.append("Age must be between 1 and 120 years.")
        if not (100.0 <= height <= 250.0):
            errors.append("Height must be between 100 and 250 cm.")
        if not (20.0 <= weight <= 250.0):
            errors.append("Weight must be between 20 and 250 kg.")
        

        if errors:
            for e in errors:
                st.error(f"\u26a0\ufe0f {e}")
        else:
            gender_val   = 1 if gender == "Male" else 0
            bmi_computed = round(weight / ((height / 100) ** 2), 2)

            input_dict = {
                "Age":                      age,
                "Gender":                   gender_val,
                "BMI":                      bmi_computed,
                "Systolic_BP":              systolic_bp,
                "Diastolic_BP":             diastolic_bp,
                "Heart_Rate":               heart_rate,
                "Serum_Creatinine":         serum_creatinine,
                "Blood_Urea_Nitrogen":      bun,
                "eGFR":                     egfr,
                "Urine_Specific_Gravity":   usg,
                "Urine_Albumin":            urine_alb,
                "Urine_Protein":            urine_prot,
                "Albumin_Creatinine_Ratio": acr,
                "Sodium":                   sodium,
                "Potassium":                potassium,
                "Calcium":                  calcium,
                "Phosphorus":               phosphorus,
                "Chloride":                 chloride,
                "Bicarbonate":              bicarbonate,
                "Hemoglobin":               hemoglobin,
                "RBC_Count":                rbc_count,
                "WBC_Count":                wbc_count,
                "Platelet_Count":           platelet_count,
                "Packed_Cell_Volume":       pcv,
                "Blood_Glucose_Random":     bgr,
                "Fasting_Glucose":          fasting_gluc,
                "HbA1c":                    hba1c,
                "Cholesterol":              cholesterol,
                "Triglycerides":            triglycerides,
                "Serum_Albumin":            serum_albumin,
                "Total_Protein":            total_protein,
                "Diabetes":                 diabetes,
                "Hypertension":             hypertension,
                "Smoking_Status":           smoking_status,
                "Family_History_Kidney":    family_hist,
            }

            with st.spinner("\U0001f504 Analysing kidney health risk\u2026"):
                time.sleep(0.4)
                try:
                    input_df       = preprocess_single_input(input_dict, bundle["encoders"], bundle["scaler"])
                    label, proba   = predict_single(input_df, bundle)
                    emoji          = stage_emoji(label)
                    conf_val       = float(proba.max() * 100) if proba is not None else 0.0
                    conf_text      = f"<div class='confidence'>Confidence: {conf_val:.1f}%</div>" if proba is not None else ""

                    # ── Result Card ───────────────────────────────────────
                    st.markdown(f"""
                    <div class='prediction-card'>
                        <div class='stage-label'>Predicted CKD Stage</div>
                        <div class='stage-value'>{emoji} {label}</div>
                        {conf_text}
                    </div>""", unsafe_allow_html=True)

                    # ── Save to Database ──────────────────────────────────
                    try:
                        save_prediction(
                            username        = st.session_state.get("username", ""),
                            patient_name    = patient_name.strip(),
                            prediction_label= label,
                            confidence      = conf_val,
                            features_dict   = input_dict,
                        )
                    except Exception as db_err:
                        st.warning(f"\u26a0\ufe0f Could not save to history: {db_err}")

                    # ── Explainable AI ────────────────────────────────────
                    st.markdown("<br>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>\U0001f9e0 Explainable AI \u2013 Top Feature Influences</div>",
                                unsafe_allow_html=True)
                    try:
                        explanations = explain_prediction_local(input_df, bundle)
                        top5     = explanations[:5]
                        max_abs  = max((abs(v) for _, v in top5), default=1.0) or 1.0

                        fi_html = ""
                        for feat, contrib in top5:
                            dname    = FEATURE_LABELS.get(feat, feat)
                            bar_pct  = abs(contrib) / max_abs * 100
                            bar_col  = "#68d391" if contrib >= 0 else "#fc8181"
                            direction= "\u25b2 raises risk" if contrib > 0 else "\u25bc lowers risk"
                            fi_html += f"""<div class='fi-row'>
<div class='fi-label'>{dname}</div>
<div class='fi-bar-outer'>
<div class='fi-bar-inner' style='width:{bar_pct:.1f}%;background:{bar_col};'></div>
</div>
<div class='fi-value' style='color:{bar_col};'>{contrib:+.3f}</div>
<div style='font-size:0.72rem;color:#718096;width:90px;'>{direction}</div>
</div>"""

                        st.markdown(f"""<div class='fi-bar-container'>
<div style='font-size:0.82rem;color:#a0aec0;margin-bottom:14px;'>
Each bar shows how much a feature shifted the prediction probability
versus the population average.
</div>
{fi_html}
</div>""", unsafe_allow_html=True)

                        # Plotly full feature chart
                        feat_names  = [FEATURE_LABELS.get(f, f) for f, _ in explanations]
                        feat_vals   = [v for _, v in explanations]
                        feat_colors = ["#68d391" if v >= 0 else "#fc8181" for v in feat_vals]

                        fig_fi = go.Figure(go.Bar(
                            x=feat_vals, y=feat_names, orientation="h",
                            marker_color=feat_colors,
                            text=[f"{v:+.4f}" for v in feat_vals],
                            textposition="outside",
                        ))
                        fig_fi.update_layout(
                            title="Feature Influence on Prediction (All Features)",
                            xaxis_title="Influence Score",
                            height=380,
                            margin=dict(l=0, r=60, t=40, b=20),
                            paper_bgcolor="rgba(0,0,0,0)",
                            plot_bgcolor="rgba(30,37,53,0.6)",
                            font=dict(color="#a0aec0", size=12),
                            xaxis=dict(gridcolor="#2d3748", zerolinecolor="#4a5568"),
                            yaxis=dict(gridcolor="#2d3748"),
                        )
                        st.plotly_chart(fig_fi, width='stretch')

                    except Exception as ex_err:
                        st.warning(f"\u26a0\ufe0f Feature importance unavailable: {ex_err}")

                    # ── Recommendations ───────────────────────────────────
                    st.markdown("<br>", unsafe_allow_html=True)
                    st.markdown("<div class='section-header'>\U0001f4a1 Personalized Health Recommendations</div>",
                                unsafe_allow_html=True)
                    recs = generate_detailed_recommendations(input_dict, label)
                    for title, desc in recs:
                        st.info(f"**{title}:** {desc}")

                    # ── Confidence Bar Chart ──────────────────────────────
                    if proba is not None:
                        st.markdown("<br>", unsafe_allow_html=True)
                        st.markdown("#### \U0001f4ca Prediction Confidence per Stage")
                        classes = bundle["classes"]
                        colors  = [STAGE_COLORS.get(c, "#63b3ed") for c in classes]

                        fig_conf = go.Figure(go.Bar(
                            x=list(proba * 100), y=list(classes), orientation="h",
                            marker_color=colors,
                            text=[f"{p*100:.1f}%" for p in proba],
                            textposition="outside",
                        ))
                        fig_conf.update_layout(
                            xaxis=dict(title="Probability (%)", range=[0, 115], gridcolor="#2d3748"),
                            yaxis=dict(gridcolor="#2d3748"),
                            height=300,
                            margin=dict(l=0, r=60, t=20, b=20),
                            paper_bgcolor="rgba(0,0,0,0)",
                            plot_bgcolor="rgba(30,37,53,0.6)",
                            font=dict(color="#a0aec0", size=12),
                        )
                        st.plotly_chart(fig_conf, width='stretch')

                    # ── PDF & Email ───────────────────────────────────────
                    st.markdown("<br>", unsafe_allow_html=True)
                    pdf_result = create_pdf_report(
                        input_dict, label, conf_val, recs,
                        patient_name=patient_name.strip())
                    if isinstance(pdf_result, str):
                        pdf_bytes = pdf_result.encode("latin-1", errors="ignore")
                    else:
                        pdf_bytes = bytes(pdf_result)
                    pdf_filename = (
                        f"CKD_Report_{patient_name.strip().replace(' ','_')}_"
                        f"{datetime.datetime.now().strftime('%Y%m%d')}.pdf"
                    )

                    col_dl, col_em = st.columns(2)
                    with col_dl:
                        st.download_button(
                            label="\U0001f4c4 Download PDF Report",
                            data=pdf_bytes,
                            file_name=pdf_filename,
                            mime="application/pdf",
                            width='stretch',
                        )
                    with col_em:
                        with st.expander("\U0001f4e7 Email Report"):
                            email_addr = st.text_input("Recipient Email", key="email_addr",
                                                        placeholder="patient@example.com")
                            if st.button("Send Email", key="send_email_btn"):
                                if not email_addr or "@" not in email_addr:
                                    st.error("Please enter a valid email address.")
                                else:
                                    ok, status, path = send_pdf_email(email_addr, pdf_bytes, pdf_filename)
                                    if ok and status == "dry_run":
                                        st.success("\u2705 Dry-run: email saved to `ckd_email_report.eml` (no SMTP configured).")
                                    elif ok:
                                        st.success("\u2705 Email sent successfully!")
                                    else:
                                        st.error(f"\u274c Failed to send email: {status}")

                    # ── Feedback Form ─────────────────────────────────────
                    st.markdown("<br>", unsafe_allow_html=True)
                    st.markdown("#### 💬 Rate this Prediction")
                    with st.form("feedback_form"):
                        rating = st.slider("Rating (1 = Poor, 5 = Excellent)", min_value=1, max_value=5, value=5)
                        comments = st.text_area("Additional Feedback", placeholder="How accurate is this prediction based on clinical judgement?")
                        fb_submitted = st.form_submit_button("Submit Feedback", width='stretch')
                        if fb_submitted:
                            submit_feedback(username, rating, comments, pred_id)
                            st.success("Thank you for your feedback! It has been recorded for model auditing.")

                except Exception as ex:
                    st.error(f"\u274c Prediction error: {ex}")


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: HISTORY
# ═════════════════════════════════════════════════════════════════════════════
elif page == "📋  History":
    st.markdown("<h1 style='color:#e2e8f0;'>\U0001f4cb Prediction History</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#a0aec0;'>View, search, and filter all past CKD predictions made under your account.</p>",
                unsafe_allow_html=True)

    username = st.session_state.get("username", "")
    st.markdown("---")

    fc1, fc2, fc3, fc4 = st.columns([2, 1.5, 1.5, 1])
    with fc1:
        search_query = st.text_input("\U0001f50d Search by Patient Name", placeholder="Type a name\u2026", key="hist_search")
    with fc2:
        start_date = st.date_input("From Date", value=None, key="hist_start")
    with fc3:
        end_date   = st.date_input("To Date",   value=None, key="hist_end")
    with fc4:
        st.markdown("<br>", unsafe_allow_html=True)
        clear_filters = st.button("\U0001f504 Reset", width='stretch', key="hist_reset")

    if clear_filters:
        for k in ["hist_search", "hist_start", "hist_end"]:
            if k in st.session_state:
                del st.session_state[k]
        st.rerun()

    start_str = str(start_date) if start_date else None
    end_str   = str(end_date)   if end_date   else None

    rows = get_predictions(username,
                           search_query=search_query or None,
                           start_date=start_str,
                           end_date=end_str)

    st.markdown("<br>", unsafe_allow_html=True)

    if not rows:
        st.info("\U0001f4ed No prediction records found. Make a prediction first!")
    else:
        total_count = len(rows)
        st.markdown(f"""
        <div style='margin-bottom:12px;font-size:0.9rem;color:#a0aec0;'>
            Showing <strong style='color:#63b3ed;'>{total_count}</strong> record(s)
        </div>
        """, unsafe_allow_html=True)

        display_rows = []
        for r in rows:
            display_rows.append({
                "Date":         r.get("created_at", "")[:16],
                "Patient":      r.get("patient_name", "Unknown"),
                "Age":          r.get("Age", "N/A"),
                "Gender":       "Male" if r.get("Gender") == 1 else "Female",
                "BMI":          f"{r.get('BMI', 0):.1f}",
                "Diabetes":     r.get("Diabetes", "N/A"),
                "Hypertension": r.get("Hypertension", "N/A"),
                "Prediction":   r.get("prediction_label", "Unknown"),
                "Confidence":   f"{r.get('confidence', 0):.1f}%",
            })

        df_hist = pd.DataFrame(display_rows)

        def color_prediction(val):
            color_map = {
                "Healthy Kidney":          "#68d391",
                "Mild CKD (Stage 1\u20132)": "#f6e05e",
                "Moderate CKD (Stage 3)":  "#ed8936",
                "Severe CKD (Stage 4)":    "#fc8181",
                "Kidney Failure (Stage 5)":"#e53e3e",
            }
            return f"color:{color_map.get(val,'#a0aec0')};font-weight:600;"

        styled_df = df_hist.style.map(color_prediction, subset=["Prediction"])
        st.dataframe(styled_df, width='stretch', hide_index=True)

        # ── Export History Options ──────────────────────────────────────────
        col_csv, col_xlsx = st.columns(2)
        with col_csv:
            csv_data = df_hist.to_csv(index=False).encode('utf-8')
            st.download_button(
                label="📥 Export History to CSV",
                data=csv_data,
                file_name=f"CKD_Prediction_History_{datetime.datetime.now().strftime('%Y%m%d')}.csv",
                mime="text/csv",
                width='stretch'
            )
        with col_xlsx:
            import io
            buffer = io.BytesIO()
            try:
                with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                    df_hist.to_excel(writer, index=False, sheet_name='Prediction History')
                st.download_button(
                    label="📥 Export History to Excel",
                    data=buffer.getvalue(),
                    file_name=f"CKD_Prediction_History_{datetime.datetime.now().strftime('%Y%m%d')}.xlsx",
                    mime="application/vnd.ms-excel",
                    width='stretch'
                )
            except Exception as e:
                # Fallback to CSV format if openpyxl fails
                st.download_button(
                    label="📥 Export History to Excel (CSV Fallback)",
                    data=csv_data,
                    file_name=f"CKD_Prediction_History_{datetime.datetime.now().strftime('%Y%m%d')}.csv",
                    mime="text/csv",
                    width='stretch'
                )

        # ── Patient Progress Tracking over Time ─────────────────────────────
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("### 📈 Patient Progress Tracking")
        unique_patients = list(df_hist["Patient"].unique())
        selected_p = st.selectbox("Select Patient to Plot Progress", ["-- Choose a Patient --"] + unique_patients)
        
        if selected_p != "-- Choose a Patient --":
            p_rows = [r for r in rows if r["patient_name"] == selected_p]
            p_rows.sort(key=lambda x: x["created_at"]) # Chronological order
            
            p_df_progress = pd.DataFrame(p_rows)
            p_df_progress["Date"] = pd.to_datetime(p_df_progress["created_at"])
            
            col_g1, col_g2 = st.columns(2)
            
            # eGFR Progress
            if "eGFR" in p_df_progress.columns:
                fig_egfr = px.line(p_df_progress, x="Date", y="eGFR", title=f"eGFR Trend for {selected_p}",
                                   markers=True, line_shape="linear")
                fig_egfr.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(30,37,53,0.6)",
                                       font=dict(color="#a0aec0"), height=300)
                col_g1.plotly_chart(fig_egfr, use_container_width=True)
                
            # Serum Creatinine Progress
            if "Serum_Creatinine" in p_df_progress.columns:
                fig_creat = px.line(p_df_progress, x="Date", y="Serum_Creatinine", title=f"Serum Creatinine Trend for {selected_p}",
                                    markers=True, line_shape="linear")
                fig_creat.update_layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(30,37,53,0.6)",
                                        font=dict(color="#a0aec0"), height=300)
                col_g2.plotly_chart(fig_creat, use_container_width=True)

        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("#### \U0001f5c2\ufe0f Detailed Records")
        for r in rows[:10]:
            row = normalize_prediction_row(r)
            emoji   = stage_emoji(row["prediction_label"])
            s_color = stage_color_hex(row["prediction_label"])
            with st.expander(f"{emoji}  {row['patient_name']} \u2014 {row['prediction_label']}  \u00b7  {row['created_at'][:16]}"):
                d1, d2, d3 = st.columns(3)
                d1.metric("Age",    row.get("Age", row.get("age", "N/A")))
                d2.metric("Gender", row.get("Gender", row.get("gender", "N/A")))
                d3.metric("BMI",    f"{row.get('BMI', row.get('bmi', 0)):.1f}")
                d4, d5, d6 = st.columns(3)
                d4.metric("Systolic BP", row.get("Systolic_BP", 0))
                d5.metric("eGFR", row.get("eGFR", 0))
                d6.metric("Serum Creatinine", row.get("Serum_Creatinine", 0))
                d7, d8, d9 = st.columns(3)
                d7.metric("Diabetes",     row.get("Diabetes", row.get("diabetes", "N/A")))
                d8.metric("Hypertension", row.get("Hypertension", row.get("hypertension", "N/A")))
                d9.metric("Family Hist.", row.get("Family_History_Kidney", row.get("family_history", "N/A")))
                st.markdown(f"""
                <div style='margin-top:12px;padding:12px 20px;
                            background:rgba(49,130,206,0.1);border-radius:10px;
                            border-left:4px solid {s_color};'>
                    <span style='color:{s_color};font-weight:700;font-size:1.1rem;'>{emoji} {row["prediction_label"]}</span>
                    <span style='color:#a0aec0;font-size:0.9rem;margin-left:16px;'>Confidence: {row["confidence"]:.1f}%</span>
                </div>""", unsafe_allow_html=True)


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: DASHBOARD
# ═════════════════════════════════════════════════════════════════════════════
elif page == "📊  Dashboard":
    st.markdown("<h1 style='color:#e2e8f0;'>\U0001f4ca Analytics Dashboard</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#a0aec0;'>Overview of predictions, model performance, and population statistics.</p>",
                unsafe_allow_html=True)
    st.markdown("---")

    username  = st.session_state.get("username", "")
    all_preds = get_predictions(username)

    total_pred = len(all_preds)
    ckd_count  = sum(1 for r in all_preds if "Healthy" not in r["prediction_label"])
    healthy_ct = total_pred - ckd_count
    avg_conf   = (sum(r["confidence"] for r in all_preds) / total_pred) if total_pred else 0.0

    m1, m2, m3, m4 = st.columns(4)
    m1.markdown(f"<div class='metric-card'><div class='metric-value'>{total_pred}</div>"
                "<div class='metric-label'>Total Predictions</div></div>", unsafe_allow_html=True)
    m2.markdown(f"<div class='metric-card'><div class='metric-value'>{ckd_count}</div>"
                "<div class='metric-label'>CKD Cases Detected</div></div>", unsafe_allow_html=True)
    m3.markdown(f"<div class='metric-card'><div class='metric-value'>{healthy_ct}</div>"
                "<div class='metric-label'>Healthy Outcomes</div></div>", unsafe_allow_html=True)
    m4.markdown(f"<div class='metric-card'><div class='metric-value'>{avg_conf:.1f}%</div>"
                "<div class='metric-label'>Avg. Confidence</div></div>", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)

    if total_pred == 0:
        st.info("\U0001f4ed No predictions yet. Make some predictions to see analytics!")
    else:
        ch1, ch2 = st.columns(2)

        with ch1:
            st.markdown("#### \U0001f369 Class Distribution")
            stage_counts = {}
            for r in all_preds:
                lbl = r["prediction_label"]
                stage_counts[lbl] = stage_counts.get(lbl, 0) + 1

            fig_pie = go.Figure(go.Pie(
                labels=list(stage_counts.keys()),
                values=list(stage_counts.values()),
                marker=dict(colors=[STAGE_COLORS.get(l, "#63b3ed") for l in stage_counts]),
                hole=0.5,
                textinfo="label+percent",
                textfont=dict(size=11),
            ))
            fig_pie.update_layout(
                height=360, margin=dict(l=0, r=0, t=20, b=20),
                paper_bgcolor="rgba(0,0,0,0)", font=dict(color="#a0aec0"),
                legend=dict(font=dict(color="#a0aec0")),
            )
            st.plotly_chart(fig_pie, width='stretch')

        with ch2:
            st.markdown("#### \U0001f4c8 Prediction Trend (Last 30 Records)")
            df_trend = pd.DataFrame(all_preds[:30][::-1])
            if "created_at" in df_trend.columns:
                df_trend["date"] = pd.to_datetime(df_trend["created_at"]).dt.date
                trend_daily = df_trend.groupby("date").size().reset_index(name="count")
                fig_trend = go.Figure(go.Scatter(
                    x=trend_daily["date"], y=trend_daily["count"],
                    mode="lines+markers",
                    line=dict(color="#63b3ed", width=2.5),
                    marker=dict(size=7, color="#63b3ed"),
                    fill="tozeroy", fillcolor="rgba(99,179,237,0.12)",
                ))
                fig_trend.update_layout(
                    xaxis=dict(title="Date", gridcolor="#2d3748"),
                    yaxis=dict(title="Predictions", gridcolor="#2d3748"),
                    height=360, margin=dict(l=0, r=20, t=20, b=20),
                    paper_bgcolor="rgba(0,0,0,0)",
                    plot_bgcolor="rgba(30,37,53,0.6)",
                    font=dict(color="#a0aec0"),
                )
                st.plotly_chart(fig_trend, width='stretch')

        st.markdown("<br>", unsafe_allow_html=True)
        ch3, ch4 = st.columns(2)

        with ch3:
            st.markdown("#### \U0001f4ca Predictions by Stage")
            all_stages = list(STAGE_COLORS.keys())
            fig_bar = go.Figure(go.Bar(
                x=all_stages,
                y=[stage_counts.get(s, 0) for s in all_stages],
                marker_color=[STAGE_COLORS[s] for s in all_stages],
                text=[stage_counts.get(s, 0) for s in all_stages],
                textposition="outside",
            ))
            fig_bar.update_layout(
                xaxis=dict(gridcolor="#2d3748", tickangle=-25),
                yaxis=dict(title="Count", gridcolor="#2d3748"),
                height=340, margin=dict(l=0, r=20, t=20, b=60),
                paper_bgcolor="rgba(0,0,0,0)",
                plot_bgcolor="rgba(30,37,53,0.6)",
                font=dict(color="#a0aec0", size=11),
            )
            st.plotly_chart(fig_bar, width='stretch')

        with ch4:
            st.markdown("#### \U0001f3af Confidence Score Distribution")
            conf_scores = [r["confidence"] for r in all_preds]
            fig_hist = go.Figure(go.Histogram(
                x=conf_scores, nbinsx=20, marker_color="#63b3ed", opacity=0.85,
            ))
            fig_hist.update_layout(
                xaxis=dict(title="Confidence (%)", gridcolor="#2d3748"),
                yaxis=dict(title="Count",          gridcolor="#2d3748"),
                height=340, margin=dict(l=0, r=20, t=20, b=20),
                paper_bgcolor="rgba(0,0,0,0)",
                plot_bgcolor="rgba(30,37,53,0.6)",
                font=dict(color="#a0aec0"),
            )
            st.plotly_chart(fig_hist, width='stretch')

        # Model Performance
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("#### \U0001f916 Model Performance Metrics")
        if model_loaded and bundle and "metrics" in bundle:
            metrics = bundle["metrics"]
            acc  = metrics.get("accuracy",  0)
            prec = metrics.get("precision", 0)
            rec  = metrics.get("recall",    0)
            f1   = metrics.get("f1",        0)

            pm1, pm2, pm3, pm4 = st.columns(4)
            pm1.markdown(f"<div class='metric-card'><div class='metric-value' style='color:#68d391;'>{acc*100:.1f}%</div>"
                         "<div class='metric-label'>Model Accuracy</div></div>", unsafe_allow_html=True)
            pm2.markdown(f"<div class='metric-card'><div class='metric-value' style='color:#63b3ed;'>{prec*100:.1f}%</div>"
                         "<div class='metric-label'>Precision</div></div>", unsafe_allow_html=True)
            pm3.markdown(f"<div class='metric-card'><div class='metric-value' style='color:#f6e05e;'>{rec*100:.1f}%</div>"
                         "<div class='metric-label'>Recall</div></div>", unsafe_allow_html=True)
            pm4.markdown(f"<div class='metric-card'><div class='metric-value' style='color:#ed8936;'>{f1*100:.1f}%</div>"
                         "<div class='metric-label'>F1-Score</div></div>", unsafe_allow_html=True)

            st.markdown("<br>", unsafe_allow_html=True)
            gc1, gc2, gc3 = st.columns([1, 2, 1])
            with gc2:
                fig_gauge = go.Figure(go.Indicator(
                    mode="gauge+number+delta",
                    value=acc * 100,
                    delta={"reference": 90, "valueformat": ".1f"},
                    number={"suffix": "%", "font": {"color": "#68d391", "size": 40}},
                    gauge={
                        "axis":   {"range": [0, 100], "tickcolor": "#a0aec0"},
                        "bar":    {"color": "#68d391"},
                        "bgcolor":"rgba(30,37,53,0.8)",
                        "steps":  [
                            {"range": [0,  60], "color": "rgba(252,129,129,0.2)"},
                            {"range": [60, 80], "color": "rgba(246,224,94,0.2)"},
                            {"range": [80,100], "color": "rgba(104,211,145,0.2)"},
                        ],
                        "threshold": {
                            "line":      {"color": "#63b3ed", "width": 4},
                            "thickness": 0.85,
                            "value":     acc * 100,
                        },
                    },
                    title={"text": "Model Accuracy", "font": {"color": "#a0aec0", "size": 15}},
                ))
                fig_gauge.update_layout(
                    height=280, margin=dict(l=20, r=20, t=30, b=20),
                    paper_bgcolor="rgba(0,0,0,0)", font=dict(color="#a0aec0"),
                )
                st.plotly_chart(fig_gauge, width='stretch')
        else:
            st.info("Model metrics not available. Ensure `train_model.py` stores metrics in the bundle.")

    # Dataset Stats
    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("#### \U0001f4c2 Dataset Statistics")
    if train_df is not None and test_df is not None:
        ds1, ds2, ds3 = st.columns(3)
        ds1.markdown(f"<div class='metric-card'><div class='metric-value'>{len(train_df):,}</div>"
                     "<div class='metric-label'>Training Samples</div></div>", unsafe_allow_html=True)
        ds2.markdown(f"<div class='metric-card'><div class='metric-value'>{len(test_df):,}</div>"
                     "<div class='metric-label'>Testing Samples</div></div>", unsafe_allow_html=True)
        ds3.markdown(f"<div class='metric-card'><div class='metric-value'>{len(train_df.columns)}</div>"
                     "<div class='metric-label'>Features</div></div>", unsafe_allow_html=True)

        target_col = [c for c in train_df.columns
                      if c.lower() in ("ckd_stage", "stage", "label", "target")]
        if target_col:
            st.markdown("<br>", unsafe_allow_html=True)
            st.markdown("#### \U0001f3f7\ufe0f Training Set Class Balance")
            vc = train_df[target_col[0]].value_counts()
            fig_tc = go.Figure(go.Bar(
                x=list(vc.index.astype(str)),
                y=list(vc.values),
                marker_color=[STAGE_COLORS.get(str(k), "#63b3ed") for k in vc.index],
                text=list(vc.values),
                textposition="outside",
            ))
            fig_tc.update_layout(
                xaxis=dict(gridcolor="#2d3748", tickangle=-20),
                yaxis=dict(title="Count", gridcolor="#2d3748"),
                height=300, margin=dict(l=0, r=20, t=20, b=60),
                paper_bgcolor="rgba(0,0,0,0)",
                plot_bgcolor="rgba(30,37,53,0.6)",
                font=dict(color="#a0aec0", size=11),
            )
            st.plotly_chart(fig_tc, width='stretch')
    else:
        st.info("Dataset files not found. Ensure the CSVs are present in the `dataset/` folder.")


# ═════════════════════════════════════════════════════════════════════════════
# PAGE: ABOUT
# ═════════════════════════════════════════════════════════════════════════════
elif page == "👤  Patients":
    st.markdown("<h1 style='color:#e2e8f0;'>👤 Patient Profile Management</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#a0aec0;'>Create, edit, delete, and view secure clinical profiles of your patients.</p>", unsafe_allow_html=True)
    st.markdown("---")
    
    username = st.session_state.get("username", "")
    
    # Tabs for creation vs viewing
    p_tab1, p_tab2 = st.tabs(["📋 View Patients", "➕ Add / Edit Patient"])
    
    with p_tab2:
        st.subheader("Patient Clinical Details")
        
        # Check if we are editing an existing patient
        edit_mode = st.checkbox("Enable Edit Mode (select existing patient)", key="edit_mode_cb")
        patients_list = get_patients(username)
        
        selected_p_id = None
        p_name = ""
        p_age = 45
        p_gender = "Male"
        p_height = 170.0
        p_weight = 70.0
        p_diabetes = "No"
        p_hypertension = "No"
        p_smoking = "No"
        p_family = "No"
        
        if edit_mode and patients_list:
            p_opts = {f"{p['name']} (ID: {p['id']})": p for p in patients_list}
            chosen_p_str = st.selectbox("Select Patient to Edit", list(p_opts.keys()))
            chosen_p = p_opts[chosen_p_str]
            selected_p_id = chosen_p["id"]
            p_name = chosen_p["name"]
            p_age = int(chosen_p["age"])
            p_gender = chosen_p["gender"]
            p_height = float(chosen_p["height"])
            p_weight = float(chosen_p["weight"])
            p_diabetes = chosen_p["diabetes"]
            p_hypertension = chosen_p["hypertension"]
            p_smoking = chosen_p["smoking_status"]
            p_family = chosen_p["family_history"]
        
        with st.form("patient_form"):
            name = st.text_input("Patient Name", value=p_name)
            col1, col2 = st.columns(2)
            age = col1.number_input("Age (years)", min_value=1, max_value=120, value=p_age)
            gender = col2.selectbox("Gender", ["Male", "Female"], index=0 if p_gender == "Male" else 1)
            
            col3, col4 = st.columns(2)
            height = col3.number_input("Height (cm)", min_value=100.0, max_value=250.0, value=p_height, step=0.5)
            weight = col4.number_input("Weight (kg)", min_value=20.0, max_value=250.0, value=p_weight, step=0.5)
            
            col5, col6 = st.columns(2)
            diabetes = col5.selectbox("Diabetes", ["No", "Yes"], index=0 if p_diabetes == "No" else 1)
            hypertension = col6.selectbox("Hypertension", ["No", "Yes"], index=0 if p_hypertension == "No" else 1)
            
            col7, col8 = st.columns(2)
            smoking = col7.selectbox("Smoking Status", ["No", "Yes"], index=0 if p_smoking == "No" else 1)
            family = col8.selectbox("Family History of Kidney Disease", ["No", "Yes"], index=0 if p_family == "No" else 1)
            
            submit_lbl = "Update Patient Profile" if edit_mode else "Save Patient Profile"
            submitted = st.form_submit_button(submit_lbl, width='stretch')
            
            if submitted:
                if not name.strip():
                    st.error("Patient name cannot be empty.")
                else:
                    if edit_mode and selected_p_id:
                        update_patient(username, selected_p_id, name.strip(), age, gender, height, weight, diabetes, hypertension, smoking, family)
                        st.success(f"🎉 Patient profile '{name}' updated successfully!")
                    else:
                        create_patient(username, name.strip(), age, gender, height, weight, diabetes, hypertension, smoking, family)
                        st.success(f"🎉 New patient profile '{name}' created successfully!")
                    time.sleep(0.5)
                    st.rerun()

    with p_tab1:
        st.subheader("Registered Patients")
        patients_list = get_patients(username)
        if not patients_list:
            st.info("No patient profiles registered yet.")
        else:
            p_df = pd.DataFrame(patients_list)
            # Reorder for display
            display_cols = ["id", "name", "age", "gender", "height", "weight", "diabetes", "hypertension", "smoking_status", "family_history", "created_at"]
            p_df = p_df[[c for c in display_cols if c in p_df.columns]]
            st.dataframe(p_df, width='stretch', hide_index=True)
            
            # Action to Delete
            st.markdown("<br>", unsafe_allow_html=True)
            st.subheader("Delete Patient Profile")
            delete_opts = {f"{p['name']} (ID: {p['id']})": p['id'] for p in patients_list}
            p_to_delete = st.selectbox("Select Patient to Remove", list(delete_opts.keys()), key="delete_p_select")
            if st.button("Delete Profile", type="primary"):
                delete_patient(username, delete_opts[p_to_delete])
                st.success(f"🗑️ Profile removed.")
                time.sleep(0.5)
                st.rerun()

elif page == "📅  Reminders":
    st.markdown("<h1 style='color:#e2e8f0;'>📅 Appointment Reminders</h1>", unsafe_allow_html=True)
    st.markdown("<p style='color:#a0aec0;'>Schedule and track follow-up appointments and reminders for your patients.</p>", unsafe_allow_html=True)
    st.markdown("---")
    
    username = st.session_state.get("username", "")
    patients_list = get_patients(username)
    
    col_sch, col_rem = st.columns([1.2, 1.8])
    
    with col_sch:
        st.subheader("Schedule Appointment")
        if not patients_list:
            st.warning("⚠️ Please register at least one patient under the Patients tab before scheduling appointments.")
        else:
            p_names = [p['name'] for p in patients_list]
            with st.form("appt_form"):
                p_name = st.selectbox("Select Patient", p_names)
                appt_date = st.date_input("Appointment Date")
                appt_time = st.time_input("Appointment Time", value=datetime.time(10, 0))
                notes = st.text_area("Notes / Reasons for Follow-up", placeholder="e.g. Routine blood test, eGFR review...")
                
                submitted = st.form_submit_button("Confirm Schedule", width='stretch')
                if submitted:
                    datetime_str = f"{appt_date} {appt_time.strftime('%H:%M:%S')}"
                    schedule_appointment(username, p_name, datetime_str, notes)
                    st.success(f"📅 Appointment scheduled for {p_name} on {appt_date} at {appt_time.strftime('%H:%M')}!")
                    time.sleep(0.5)
                    st.rerun()

    with col_rem:
        st.subheader("Upcoming Reminders & Appointments")
        appointments = get_appointments(username)
        if not appointments:
            st.info("No upcoming appointments scheduled.")
        else:
            for appt in appointments:
                # Highlight in orange if date is today/past
                st.markdown(f"""
                <div style='padding:14px 20px;background:#1e2535;border:1px solid #2d3748;
                            border-radius:10px;margin-bottom:12px;border-left:4px solid #ed8936;'>
                    <strong style='color:#e2e8f0;font-size:1rem;'>👤 {appt['patient_name']}</strong>
                    <div style='font-size:0.82rem;color:#a0aec0;margin-top:4px;'>📅 Date: {appt['appointment_date']}</div>
                    <div style='font-size:0.85rem;color:#cbd5e0;margin-top:6px;'>📝 Notes: {appt['notes']}</div>
                </div>
                """, unsafe_allow_html=True)
                if st.button(f"Cancel Appointment (ID: {appt['id']})", key=f"cancel_{appt['id']}"):
                    delete_appointment(username, appt['id'])
                    st.success("Appointment cancelled successfully.")
                    time.sleep(0.5)
                    st.rerun()

elif page == "🔑  Admin Panel":
    if st.session_state.get("username") != "admin":
        st.error("Access denied. Admin authorization required.")
    else:
        st.markdown("<h1 style='color:#e2e8f0;'>🔑 Admin Dashboard & Audit System</h1>", unsafe_allow_html=True)
        st.markdown("<p style='color:#a0aec0;'>System statistics, user management, and security audit logs.</p>", unsafe_allow_html=True)
        st.markdown("---")
        
        metrics = get_admin_metrics()
        
        # Display system metrics cards
        col_m1, col_m2, col_m3 = st.columns(3)
        col_m1.markdown(f"""<div class='metric-card'><div class='metric-value'>{metrics['total_users']}</div>
                         <div class='metric-label'>Registered Clinicians / Users</div></div>""", unsafe_allow_html=True)
        col_m2.markdown(f"""<div class='metric-card'><div class='metric-value'>{metrics['total_predictions']}</div>
                         <div class='metric-label'>Total Predictions Generated</div></div>""", unsafe_allow_html=True)
        col_m3.markdown(f"""<div class='metric-card'><div class='metric-value'>1.0.1</div>
                         <div class='metric-label'>System / Model Version</div></div>""", unsafe_allow_html=True)
        
        st.markdown("<br>", unsafe_allow_html=True)
        
        adm_tab1, adm_tab2, adm_tab3 = st.tabs(["🛡️ Security Audit Logs", "👤 User Management", "💬 Patient Feedback"])
        
        with adm_tab1:
            st.subheader("System Access & Action Audit Logs")
            logs = get_audit_logs()
            if not logs:
                st.info("No audit logs recorded.")
            else:
                log_df = pd.DataFrame(logs)
                st.dataframe(log_df, width='stretch', hide_index=True)
                
        with adm_tab2:
            st.subheader("Registered Clinicians")
            user_df = pd.DataFrame(metrics["users_list"])
            st.dataframe(user_df, width='stretch', hide_index=True)
            
        with adm_tab3:
            st.subheader("User & Patient Ratings")
            feedback = get_all_feedback()
            if not feedback:
                st.info("No feedback submitted yet.")
            else:
                for fb in feedback:
                    stars = "⭐️" * int(fb['rating'])
                    st.markdown(f"""
                    <div style='padding:14px 20px;background:#1e2535;border:1px solid #2d3748;
                                border-radius:10px;margin-bottom:12px;'>
                        <strong style='color:#e2e8f0;font-size:0.95rem;'>User: {fb['username']} | Rating: {stars}</strong>
                        <div style='font-size:0.82rem;color:#cbd5e0;margin-top:6px;'>💭 Comments: {fb['comments']}</div>
                        <div style='font-size:0.75rem;color:#a0aec0;margin-top:4px;'>📅 Time: {fb['created_at']}</div>
                    </div>
                    """, unsafe_allow_html=True)

elif page == "ℹ️  About":
    st.markdown("<h1 style='color:#e2e8f0;'>\u2139\ufe0f About This System</h1>", unsafe_allow_html=True)

    st.markdown("<div class='section-header'>\U0001fac1 What is Chronic Kidney Disease?</div>",
                unsafe_allow_html=True)
    st.markdown("""
<div style='background:#1e2535;border-radius:12px;padding:24px;border:1px solid #2d3748;color:#cbd5e0;line-height:1.8;'>

**Chronic Kidney Disease (CKD)** is a long-term condition where the kidneys gradually lose their
filtering ability over months or years.

CKD is classified into five stages based on **eGFR (estimated Glomerular Filtration Rate)**:

| Stage | eGFR Range        | Description                  |
|-------|-------------------|------------------------------|
| 1-2   | >= 60 mL/min      | Mild - kidney damage present |
| 3     | 30-59 mL/min      | Moderate reduction           |
| 4     | 15-29 mL/min      | Severe reduction             |
| 5     | < 15 mL/min       | Kidney failure               |

**Risk factors** include diabetes, hypertension, family history, obesity, and smoking.
</div>
""", unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    st.markdown("<div class='section-header'>&#9881;&#65039; Technology Stack</div>", unsafe_allow_html=True)
    t1, t2, t3 = st.columns(3)
    t1.markdown("<div class='metric-card'><div style='font-size:2rem;'>\U0001f916</div>"
                "<div class='metric-label' style='margin-top:8px;'>Machine Learning</div>"
                "<div style='font-size:0.82rem;color:#a0aec0;margin-top:4px;'>Random Forest<br>Scikit-learn</div></div>",
                unsafe_allow_html=True)
    t2.markdown("<div class='metric-card'><div style='font-size:2rem;'>\U0001f310</div>"
                "<div class='metric-label' style='margin-top:8px;'>Frontend</div>"
                "<div style='font-size:0.82rem;color:#a0aec0;margin-top:4px;'>Streamlit \u00b7 Plotly<br>HTML/CSS</div></div>",
                unsafe_allow_html=True)
    t3.markdown("<div class='metric-card'><div style='font-size:2rem;'>\U0001f4be</div>"
                "<div class='metric-label' style='margin-top:8px;'>Storage &amp; Reports</div>"
                "<div style='font-size:0.82rem;color:#a0aec0;margin-top:4px;'>SQLite \u00b7 FPDF2<br>PDF Generation</div></div>",
                unsafe_allow_html=True)

    st.markdown("<br>", unsafe_allow_html=True)
    st.warning("""
    \u26a0\ufe0f **Medical Disclaimer**: This application is intended for **educational and research purposes only**.
    It is **not a substitute** for professional medical advice, diagnosis, or treatment.
    Always consult a qualified healthcare provider for medical decisions.
    """)
